spring:
  mariadb:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3307/study?characterEncoding=UTF-8&serverTimezone=UTC
      username: study
      password: 1234

  config:
    import: 'classpath:/application-secret.yml'

  main:
    allow-bean-definition-overriding: true
#    web-application-type: reactive

  devtools:
    livereload:
      enabled: true

  web-flux:
    base-path: /v1/api

  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.example.demo

server:
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false

custom:
  reactive: false
  mvc:
    enabled: false
